services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     
      - "15672:15672"   
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - uniguairaca_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:

networks:
  uniguairaca_network: 
    driver: bridge
    name: uniguairaca_network 